#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/root/trelloapp-vue-vite-ts/node_modules/.pnpm/esbuild@0.14.54/node_modules/esbuild/bin/node_modules:/root/trelloapp-vue-vite-ts/node_modules/.pnpm/esbuild@0.14.54/node_modules/esbuild/node_modules:/root/trelloapp-vue-vite-ts/node_modules/.pnpm/esbuild@0.14.54/node_modules:/root/trelloapp-vue-vite-ts/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/root/trelloapp-vue-vite-ts/node_modules/.pnpm/esbuild@0.14.54/node_modules/esbuild/bin/node_modules:/root/trelloapp-vue-vite-ts/node_modules/.pnpm/esbuild@0.14.54/node_modules/esbuild/node_modules:/root/trelloapp-vue-vite-ts/node_modules/.pnpm/esbuild@0.14.54/node_modules:/root/trelloapp-vue-vite-ts/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../bin/esbuild" "$@"
else
  exec node  "$basedir/../../bin/esbuild" "$@"
fi
